steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['config', 'current-context']
  volumes:
  - name: 'kube'
    path: '/kube'
  env:
  - 'KUBECONFIG=/kube/config'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gcp-policy-management'
  - 'CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS=true'
- name: 'gcr.io/optimistic-balm-233816/bespin-cloudbuild:dev'
  args: ['https://api.github.com/repos/lee-schumacher/gcp-policy-management-tutorial', '$COMMIT_SHA']
  secretEnv: ['TOKEN']
  volumes:
  - name: 'kube'
    path: '/kube'
  env:
  - 'KUBECONFIG=/kube/config'

secrets:
- kmsKeyName: projects/optimistic-balm-233816/locations/global/keyRings/cloudbuilder-keyring/cryptoKeys/cloudbuilder-key
  secretEnv:
    TOKEN: CiQA3mq2GgvF7d5ALWph5biXXVepWVhxiNXxzEKqBWWDpvNMDvwSUgBB3B6gWqdvPrzZWSm9ON2bSolnpMY+e+dbRN/D6LNpNiq5tDnJps5D96iLVZdLMYHAQ4pnQBbm2RsiKzDQf/Ua3ys4pa91PeKC6LxwH1aaV0A=
timeout: 30s
